---
title: "hw03"
output: github_document
author: Andy Liu
---

```{r setup, include=FALSE}
setwd("/Users/liushaoyu/Documents/hw-stat133-liushaoyusz/hw03/data")
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = 'images/')
```

2.
```{bash}

cut -d "," -f 2 nba2017-roster.csv | tail +2 | sort | uniq  > ../team-names.txt
head -n 5 ../team-names.txt

cut -d "," -f 3 nba2017-roster.csv | tail +2 | sort | uniq > ../position-names.txt
head -n 5 ../position-names.txt

#2.3
cut -d "," -f 7 nba2017-roster.csv | tail +2 | sort | uniq -c | sort -k 1 -r >  ../experience-counts.txt
head -n 5 ../experience-counts.txt

#2.4
grep -e LAC -e team nba2017-roster.csv > LAC.csv
cat LAC.csv

#2.5
grep "LAL" nba2017-roster.csv | cut -d "," -f 6 | sort | uniq -c

#2.6
grep "CLE" nba2017-roster.csv | wc -l
#2.7
grep -e GSW -e player -e height -e weight nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv
cat gsw-height-weight.csv

#2.8
cut -d "," -f 1,8 nba2017-roster.csv | sort -t "," -k 2nr -k 1r | head -n 10 > top10-salaries.csv
cat top10-salaries.csv
```

```{r}

source("../code/binomial-functions.R")
bin_probability(trials = 10, success = 3, prob = 1/6)
bin_distribution(trials = 10, prob = 0.25)
plot(bin_distribution(trials = 10, prob = 0.25),main = "plot of success and probability")

prob = 0
for(i in 4:5){
  prob = prob+bin_probability(5, i, 0.35)
}
prob

data <- bin_distribution(15,0.35)
plot(data$success,data$probability,xlab = "number of heads",ylab = "success probability")


```









