---
title: "hw03"
author: "Hao Wang"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = '../images/')
```

> 2

```{bash}
cut -f 2 -d "," ../data/../data/nba2017-roster.csv |
tail +2 |
sort -u > team-names.txt
head -5 team-names.txt
```

```{bash}
cut -f 3 -d "," ../data/../data/nba2017-roster.csv |
tail +2 |
sort -u > position-names.txt
head -5 position-names.txt
```

```{bash}
cut -f 7 -d "," ../data/../data/nba2017-roster.csv |
tail +2 |
sort |
uniq -c |
sort -nr > experience-counts.txt
head -5 experience-counts.txt
```
```{bash}
grep -e LAC -e team ../data/../data/nba2017-roster.csv > LAC.csv
cat LAC.csv
```

```{bash}
grep "LAL" ../data/nba2017-roster.csv | cut -d "," -f 6 | sort | uniq -c
```

```{bash}
grep "CLE" ../data/nba2017-roster.csv |
wc -l
```

```{bash}
grep -e GSW -e player -e height -e weight ../data/nba2017-roster.csv |
cut -d "," -f 1,4,5 > gsw-height-weight.csv

cat gsw-height-weight.csv
```

```{bash}
cut -d "," -f 1,8 ../data/nba2017-roster.csv |
sort -t "," -k 2nr -k 1r |
head -n 10 > top10-salaries.csv

(echo "player", "salary"; cat top10-salaries.csv) > tmp;
mv tmp top10-salaries.csv

cat top10-salaries.csv
```

> 3

```{r}
source("../code/binomial-functions.R")
```

```{r}
bin_probability(trials = 10, success = 3, prob = 1/6)
```

```{r}
distribution_1 <- bin_distribution(trials = 10, prob = 0.25)
plot(distribution_1, xlab = "number of heads", ylab = "success probability", main = "trials = 10, prob = 0.25")
```

```{r}
n <- c(4:5)
probability <- 0

for ( k in n ) {
  prob_k <- bin_probability(trials = 5, success = k, prob = 0.35)
  probability <- probability + prob_k
}

probability
```

```{r}
distribution_2 <- bin_distribution(trials = 15, prob = 0.35)
plot(distribution_2 , xlab = "number of heads",ylab = "success probability", main = "trials = 15, prob = 0.35")
```

